import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import { getServerSession } from "next-auth";
import { authOptions } from "@/auth";
import { AuthProvider } from "@/providers/session-provider";

const inter = Roboto({ subsets: ["latin"], weight: ["300"] });

export const metadata: Metadata = {
  title: "BH Finder",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <main className="flex flex-col h-screen ">
            <Header />
            {children}
            <Footer />
          </main>
        </AuthProvider>
      </body>
    </html>
  );
};
export default RootLayout;
